### ISSUE TITLE
Geht nicht

### ISSUE THREAD

**Issue by ppatr** [Luukeluuke/ProjektSitzplan#8]
Was ist da los

**Comment by Luukeluuke** [comment]
lass es

**Comment by ppatr** [comment]
Ich werde es nicht unterlassen

Am Mi., 8. Sept. 2021 um 22:46 Uhr schrieb Luca ***@***.***>:

**Comment by Luukeluuke** [comment]
**f**fff

**Comment by ppatr** [comment]
Kuss
